// Generated by delombok at Tue Jul 03 21:02:45 NOVT 2018
package org.statesync.protocol.subscription;

import org.statesync.protocol.RequestMessage;
import org.statesync.protocol.RequestType;

public class SubscribeAreaRequest extends RequestMessage {
	public SubscribeAreaRequest(final int id, final String area) {
		super(id, RequestType.subscribeArea, area);
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "SubscribeAreaRequest()";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof SubscribeAreaRequest)) return false;
		final SubscribeAreaRequest other = (SubscribeAreaRequest) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (!super.equals(o)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof SubscribeAreaRequest;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		int result = super.hashCode();
		return result;
	}

	@java.lang.SuppressWarnings("all")
	public SubscribeAreaRequest() {
	}
}
