// Generated by delombok at Tue Jul 03 21:02:45 NOVT 2018
package org.statesync.protocol.subscription;

import org.statesync.protocol.RequestMessage;
import org.statesync.protocol.RequestType;

public class UnsubscribeAreaRequest extends RequestMessage {
	public UnsubscribeAreaRequest(final int id, final String area) {
		super(id, RequestType.unsubscribeArea, area);
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "UnsubscribeAreaRequest()";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof UnsubscribeAreaRequest)) return false;
		final UnsubscribeAreaRequest other = (UnsubscribeAreaRequest) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (!super.equals(o)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof UnsubscribeAreaRequest;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		int result = super.hashCode();
		return result;
	}

	@java.lang.SuppressWarnings("all")
	public UnsubscribeAreaRequest() {
	}
}
