// Generated by delombok at Tue Jul 03 21:02:45 NOVT 2018
package org.statesync;

public final class ComplexDependency implements Dependency {
	public final Dependency root;
	public final String key;

	@java.lang.SuppressWarnings("all")
	public ComplexDependency(final Dependency root, final String key) {
		this.root = root;
		this.key = key;
	}

	@java.lang.SuppressWarnings("all")
	public Dependency getRoot() {
		return this.root;
	}

	@java.lang.SuppressWarnings("all")
	public String getKey() {
		return this.key;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof ComplexDependency)) return false;
		final ComplexDependency other = (ComplexDependency) o;
		final java.lang.Object this$root = this.getRoot();
		final java.lang.Object other$root = other.getRoot();
		if (this$root == null ? other$root != null : !this$root.equals(other$root)) return false;
		final java.lang.Object this$key = this.getKey();
		final java.lang.Object other$key = other.getKey();
		if (this$key == null ? other$key != null : !this$key.equals(other$key)) return false;
		return true;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $root = this.getRoot();
		result = result * PRIME + ($root == null ? 43 : $root.hashCode());
		final java.lang.Object $key = this.getKey();
		result = result * PRIME + ($key == null ? 43 : $key.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "ComplexDependency(root=" + this.getRoot() + ", key=" + this.getKey() + ")";
	}
}
